### PR TITLE
Rudimentary T::Module support

### PR DESCRIPTION
**Pull request by jez**
### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_TI52NfoQVDiTae
→ https://go/builds/bui_TI52hWcql6WKJ0
→ https://go/builds/bui_TI522GZL3MOaeK

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_TI59pUTpyStYSv

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_TIBEkkRzokG5mX
→ https://go/builds/bui_TIBEhzKlBE8ytu
→ https://go/builds/bui_TIBEH04zKbW2Cr

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_TIBLeeLOJzqUBR

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_TIW7Ypx9YrlBA3
→ https://go/builds/bui_TIW8dfFDTcEg3a
→ https://go/builds/bui_TIW8TTTDnLhUp6

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_TIWFD5CKvJfdVd

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_TJFUdaF6SOjFlJ
→ https://go/builds/bui_TJFUvP1SnEyXe4
→ https://go/builds/bui_TJFUe9eoorU0mC

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_TJFaFbd8bNKYJU

File: test/testdata/infer/generics/has_attached_class_include.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ module ChildModule1 # error: `has_attached_class!` declared by parent `Parent` m
   include Parent
 end
 
-module ChildModule2 # error: `Parent` was declared `has_attached_class!` and so cannot be `extend`ed into the module `ChildModule2
+module ChildModule2 # error: Type variance mismatch for `T.attached_class` with parent `Parent`. Parent needs to be `:out` but it is `invariant`
```
Comment (elliottt) [inline test/testdata/infer/generics/has_attached_class_include.rb:14]: This is an unfortunate error regression, is there any way to recover the old error?

File: website/docs/class-of.md [hunk 2]
```diff
@@ -368,3 +371,87 @@ T.class_of(AnotherClass)[AnotherClass, Integer]
...
+  when mod then x
+  else nil
+  end
+end
+
+data = JSON.parse(File.read('foo.json'))
+T.reveal_type(data) # => T.untyped
+
+validated = validate_against_module(data, Enumerable)
+T.reveal_type(validated) # => T::Enumerable[T.untyped]
```
Comment (elliottt) [inline website/docs/class-of.md]:
```suggestion
T.reveal_type(validated) # => T.nilable(T::Enumerable[T.untyped])
```

File: website/docs/class-of.md [hunk 3]
```diff
@@ -368,3 +371,87 @@ T.class_of(AnotherClass)[AnotherClass, Integer]
...
+
+validated = validated.map {|item| validate_against_module(item, Integer) }
+T.reveal_type(validated) # => T::Array[T.nilable(Integer)]
```
Comment (elliottt) [inline website/docs/class-of.md]:
```suggestion
validated = validated&.map {|item| validate_against_module(item, Integer) }
T.reveal_type(validated) # => T.nilable(T::Array[T.nilable(Integer)])
```

File: test/testdata/infer/generics/has_attached_class_include.rb (hunk 1 above)
Comment (elliottt) [reply test/testdata/infer/generics/has_attached_class_include.rb:14]: Reading the comment in `GlobalPass.cc`, it's not clear that there's a good way to recover this now.

File: gems/sorbet-runtime/lib/types/types/typed_module.rb [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+    end
+
+    module Private
+      module Pool
+        CACHE_FROZEN_OBJECTS =
+          begin
+            ObjectSpace::WeakMap.new[1] = 1
+            true # Ruby 2.7 and newer
+          rescue ArgumentError
+            false # Ruby 2.6 and older
```
Comment (elliottt) [inline gems/sorbet-runtime/lib/types/types/typed_module.rb:53]: Should we include this, now that we officially don't support ruby 2.x?

File: test/testdata/infer/generics/has_attached_class_include.rb (hunk 1 above)
Comment (jez) [reply test/testdata/infer/generics/has_attached_class_include.rb:14]: Yeah. It's not great but unfortunately I don't think we can do better.

After I land this stack, I will be sure to add a note to the website that it's basically impossible to use `has_attached_class!` invariantly and also correctly.

File: gems/sorbet-runtime/lib/types/types/typed_module.rb (hunk 4 above)
Comment (jez) [reply gems/sorbet-runtime/lib/types/types/typed_module.rb:53]: Pretty sure I cargo culted this from the type_class.rb file. We can consider removing them in another PR I guess, though I don't mind keeping it.

**Comment by bmulholland** [comment]
This PR appears to break tapioca. When I upgrade from sorbet 0.6.12666 to 0.6.12698, and run `tapioca gem`, I get:

```
Syncing type information for gems...
bundler: failed to load command: tapioca (/Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/bin/tapioca)
/Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/tapioca-0.17.8/lib/tapioca/runtime/trackers/required_ancestor.rb:55:in '<module:Helpers>': undefined method 'new' for module T::Module (NoMethodError)

    prepend(Module.new do
                  ^^^^
        from /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/tapioca-0.17.8/lib/tapioca/runtime/trackers/required_ancestor.rb:54:in '<module:T>'
        from /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/gems/3.4.0/gems/tapioca-0.17.8/lib/tapioca/runtime/trackers/required_ancestor.rb:53:in '<top (required)>'
        from /Users/bmulholland/.local/share/mise/installs/ruby/3.4.7/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
```

**Comment by jez** [comment]
@bmulholland It looks like tapioca is monkey patching constants owned by sorbet-runtime. Please report this to tapioca’s issue tracker.

**Comment by bmulholland** [comment]
Looks like it's [fixed](https://github.com/Shopify/tapioca/pull/2424)--thanks for the info, @jez :)
